-- Options snapshot for first installation. Generated by npm run options:dump.

-- Contains only options; no presets, settings, or local paths.

BEGIN TRANSACTION;

CREATE TABLE options (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  comment TEXT NOT NULL CHECK (length(trim(comment)) > 0),
  category TEXT NOT NULL CHECK (category IN ('world', 'items', 'challenge', 'relics', 'gameplay')),
  type TEXT NOT NULL CHECK (type IN ('char', 'short', 'word', 'long', 'string')),
  value TEXT NOT NULL CHECK (length(trim(value)) > 0),
  address TEXT CHECK (address IS NULL OR length(trim(address)) > 0),
  game_init INTEGER NOT NULL DEFAULT 0 CHECK (game_init IN (0, 1)),
  raw_json INTEGER NOT NULL DEFAULT 0 CHECK (raw_json IN (0, 1)),
  additional_writes_json TEXT CHECK (
    additional_writes_json IS NULL OR
    (json_valid(additional_writes_json) AND json_type(additional_writes_json) = 'array')
  ),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
, stat_edit INTEGER NOT NULL DEFAULT 0 CHECK (stat_edit IN (0, 1)), description TEXT NOT NULL DEFAULT '', read_only INTEGER NOT NULL DEFAULT 0 CHECK (read_only IN (0, 1)));

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (1, 'Enable Soul of Bat', 'relics', 'word', '0xa0627964', NULL, 0, 0, NULL, '2026-09-04 16:49:24', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (2, 'Enable Fire of Bat', 'relics', 'word', '0xa0627965', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (3, 'Enable Echo of Bat', 'relics', 'word', '0xa0627966', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (4, 'Enable Force of Echo', 'relics', 'word', '0xa0627967', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (5, 'Enable Soul of Wolf', 'relics', 'word', '0xa0627968', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (6, 'Enable Power of Wolf', 'relics', 'word', '0xa0627969', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (7, 'Enable Skill of Wolf', 'relics', 'word', '0xa062796a', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (8, 'Enable Form of Mist', 'relics', 'word', '0xa062796b', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (9, 'Enable Power of Mist', 'relics', 'word', '0xa062796c', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (10, 'Enable Gas Cloud', 'relics', 'word', '0xa062796d', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (11, 'Enable Cube of Zoe', 'relics', 'word', '0xa062796e', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (12, 'Enable Spirit Orb', 'relics', 'word', '0xa062796f', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (13, 'Enable Gravity Boots', 'relics', 'word', '0xa0627970', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (14, 'Enable Leap Stone', 'relics', 'word', '0xa0627971', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (15, 'Enable Holy Symbol', 'relics', 'word', '0xa0627972', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (16, 'Enable Faerie Scroll', 'relics', 'word', '0xa0627973', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (17, 'Enable Jewel of Open', 'relics', 'word', '0xa0627974', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (18, 'Enable Merman Statue', 'relics', 'word', '0xa0627975', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (19, 'Enable Bat Card', 'relics', 'word', '0xa0627976', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (20, 'Enable Ghost Card', 'relics', 'word', '0xa0627977', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (21, 'Enable Faerie Card', 'relics', 'word', '0xa0627978', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (22, 'Enable Demon Card', 'relics', 'word', '0xa0627979', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (23, 'Enable Sword Card', 'relics', 'word', '0xa062797a', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (24, 'Enable Sprite Card', 'relics', 'word', '0xa062797b', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (25, 'Enable Nosedevil Card', 'relics', 'word', '0xa062797c', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (26, 'Enable Heart of Vlad', 'relics', 'word', '0xa062797d', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (27, 'Enable Tooth of Vlad', 'relics', 'word', '0xa062797e', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (28, 'Enable Rib of Vlad', 'relics', 'word', '0xa062797f', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (29, 'Enable Ring of Vlad', 'relics', 'word', '0xa0627980', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (30, 'Enable Eye of Vlad', 'relics', 'word', '0xa0627981', NULL, 0, 0, NULL, '2026-09-04 17:01:32', '2026-09-04 17:01:32', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (31, 'Death goes home', 'world', 'word', '0x18000006', '0x4BAEA08', 0, 0, NULL, '2026-09-04 17:43:05', '2026-09-07 05:43:08', 0, 'Death takes the day (night?) off...well at least in the first castle', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (32, 'One Hit Death', 'challenge', 'word', '0x080288B1', '0x10B17C', 0, 0, '[{"type":"word","value":"0x00000000"},{"type":"word","value":"0x0C04296F","address":"0xAE2AC"},{"type":"word","value":"0x00000000"},{"type":"word","value":"0x3C088009"},{"type":"word","value":"0xA5007BA0"},{"type":"word","value":"0x0803CC4F"},{"type":"word","value":"0x00000000"}]', '2026-09-04 18:28:59', '2026-09-04 18:28:59', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (33, 'Permanent Poison', 'challenge', 'word', '0x34040000', '0x127604', 0, 0, '[{"type":"word","value":"0x0C03F6C6"},{"type":"word","value":"0x34050FFF"},{"type":"word","value":"0x3C050016"},{"type":"word","value":"0x34A5002C"},{"type":"word","value":"0x3C048007"},{"type":"word","value":"0x8C84C3B8"},{"type":"word","value":"0x00003021"},{"type":"word","value":"0x3C018007"},{"type":"word","value":"0xA4222F00"},{"type":"word","value":"0x34028164"},{"type":"word","value":"0x0C046ABF"},{"type":"word","value":"0x00000000"},{"type":"word","value":"0x08042EFE"},{"type":"word","value":"0x00000000"}]', '2026-09-04 18:39:17', '2026-09-04 18:39:17', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (34, 'No (Alucard) Spells', 'challenge', 'char', '0xFF', '0x000b5260', 0, 0, '[{"type":"char","value":"0xFF","address":"0x000b5244"},{"type":"char","value":"0xFF","address":"0x000b527c"},{"type":"char","value":"0xFF","address":"0x000b5298"},{"type":"char","value":"0xFF","address":"0x000b52d0"}]', '2026-09-04 18:59:58', '2026-09-07 05:51:00', 0, 'No Alucard spells, work on your combat!', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (35, 'Disable Wingsmash', 'challenge', 'char', '0xFF', '0x000b52ec', 0, 0, NULL, '2026-09-04 19:10:41', '2026-09-07 05:52:02', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (36, 'Infinite Wingsmash', 'gameplay', 'char', '0x00', '0x0134074', 0, 0, NULL, '2026-09-04 19:11:18', '2026-09-04 19:11:18', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (37, 'Full Screen Force of Echo', 'gameplay', 'char', '0xfe', '0x0014c8bc', 0, 0, '[{"type":"char","address":"0x0014c8c4","value":"0xf0"}]', '2026-09-04 19:13:22', '2026-09-04 19:13:22', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (38, 'Lycan Wolf Mana Costs', 'gameplay', 'short', '0x0000', '0x00118cc8', 0, 0, '[{"type":"char","address":"0x000b53b0","value":"0x01"}]', '2026-09-04 19:16:28', '2026-09-07 05:53:09', 0, 'You lycan what youre seein''?', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (39, '0 Mana Wingsmash', 'gameplay', 'char', '0x00', '0x000b52ec', 0, 0, NULL, '2026-09-04 19:18:18', '2026-09-04 19:18:18', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (40, '0 Mana Gravity Jump', 'gameplay', 'short', '0x0000', '0x118D3C', 0, 0, NULL, '2026-09-04 19:19:09', '2026-09-04 19:19:09', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (41, 'Unlocked 1st Castle Teleporters', 'world', 'word', '0x3402001F', NULL, 1, 0, '[{"type":"word","value":"0xa062BEBC"}]', '2026-09-04 20:42:15', '2026-09-07 05:44:12', 0, 'Opens all of the 1st castle teleporters, updates complexity of checks', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (42, 'Unlocked 2nd Castle Teleporters', 'world', 'word', '0x3402001F', NULL, 1, 0, '[{"type":"word","value":"0xa062BEBD"}]', '2026-09-04 20:52:31', '2026-09-08 04:13:33', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (43, 'Naked Mode', 'challenge', 'word', '{"startingEquipment": [{
    "slot": "Right hand",
    "item": null
  }, {
    "slot": "Left hand",
    "item": null
  }, {
    "slot": "Head",
    "item": null
  }, {
    "slot": "Body",
    "item": null
  }, {
    "slot": "Cloak",
    "item": null
  }, {
    "slot": "Other",
    "item": null
  }]}', NULL, 0, 1, NULL, '2026-09-04 21:41:46', '2026-09-07 05:48:19', 0, 'Arrive at the castle empty handed', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (44, 'ITS OVER 9000 Mode', 'gameplay', 'word', '0x34020063', NULL, 0, 0, '[{"type":"word","value":"0xa0627bc0"},{"type":"word","value":"0xa0627bb8"},{"type":"word","value":"0xa0627bbc"},{"type":"word","value":"0xa0627bc4"}]', '2026-09-07 04:43:51', '2026-09-07 05:46:22', 1, 'All stats to 99, after a long days work sometimes you just wanna punch things', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (45, 'Humble Beginnings', 'challenge', 'word', '0x34020001', NULL, 0, 0, '[{"type":"word","value":"0xa0627bc0"},{"type":"word","value":"0xa0627bb8"},{"type":"word","value":"0xa0627bbc"},{"type":"word","value":"0xa0627bc4"},{"type":"word","value":"0x34020014"},{"type":"word","value":"0xa0627ba0"},{"type":"word","value":"0xa0627ba4"},{"type":"word","value":"0xa0627bb4"}]', '2026-09-07 05:20:18', '2026-09-07 05:47:55', 1, 'All stats start at 1, health/mana start at 20', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (46, 'Warlock Spell Costs', 'gameplay', 'char', '0x01', '0x000b5260', 0, 0, '[{"type":"char","address":"0x000b5244","value":"0x02"},{"type":"char","address":"0x000b527c","value":"0x02"},{"type":"char","address":"0x000b5298","value":"0x03"},{"type":"char","address":"0x000b52d0","value":"0x04"}]', '2026-09-07 06:06:50', '2026-09-07 06:07:04', 0, '', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (47, 'Warlock Mist Costs', 'gameplay', 'short', '0x0000', '0x00118b34', 0, 0, '[{"type":"short","address":"0x00118ae8","value":"0x0000"}]', '2026-09-08 02:34:36', '2026-09-08 02:34:36', 0, 'Mist transform doesnt consume MP', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (48, 'Open Non-Complexity Altering Shortcuts', 'world', 'word', '0x34020001', NULL, 1, 0, '[{"type":"word","value":"0xa062BE6F"},{"type":"word","value":"0xa062BE80"},{"type":"word","value":"0xa062BE9D"},{"type":"word","value":"0xa062BDFC"},{"type":"word","value":"0xa062BE1D"}]', '2026-09-08 03:00:53', '2026-09-08 03:07:31', 0, 'Opens Alchemy Lab Cannon, Attic Stairs, Colosseum to Royal Chapel, Outer Wall Elevator', 1);

INSERT INTO "options" ("id", "comment", "category", "type", "value", "address", "game_init", "raw_json", "additional_writes_json", "created_at", "updated_at", "stat_edit", "description", "read_only") VALUES (50, 'Lycan Equipment', 'items', 'word', '{ "startingEquipment": [
    {
      "slot": "Right hand",
      "item": "Shield rod"
    },
    {
      "slot": "Left hand",
      "item": "Shaman shield"
    },
    {
      "slot": "Head",
      "item": "Silver crown"
    },
    {
      "slot": "Body",
      "item": "Brilliant mail"
    },
    {
      "slot": "Cloak",
      "item": "Blood cloak"
    },
    {
      "slot": "Other",
      "item": "Mystic pendant"
    }
  ]}', NULL, 0, 1, NULL, '2026-09-10 04:00:21', '2026-09-10 04:00:59', 0, '', 0);

DELETE FROM sqlite_sequence WHERE name = 'options';

INSERT INTO sqlite_sequence (name, seq) VALUES ('options', 50);

COMMIT;
