const { DatabaseSync } = require('node:sqlite');
const { readFileSync, writeFileSync, renameSync, rmSync } = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const dumpPath = path.join(root, 'database/options-dump.sql');
const quoteIdentifier = value => `"${value.replaceAll('"', '""')}"`;
function sqlValue(value) {
  if (value === null) return 'NULL';
  if (typeof value === 'number' || typeof value === 'bigint') return String(value);
  if (typeof value === 'string') {
    // SQLite string literals cannot contain a NUL byte.
    if (value.includes('\0')) return `CAST(X'${Buffer.from(value).toString('hex')}' AS TEXT)`;
    return `'${value.replaceAll("'", "''")}'`;
  }
  if (value instanceof Uint8Array) return `X'${Buffer.from(value).toString('hex')}'`;
  throw new Error('Unsupported SQLite value in options.');
}

function validateDump(sql) {
  const database = new DatabaseSync(':memory:');
  try {
    database.exec(sql);
    const tables = database.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'").all();
    if (tables.length !== 1 || tables[0].name !== 'options') throw new Error('Release dump must contain only the options table.');
    if (database.prepare('PRAGMA integrity_check').get().integrity_check !== 'ok') throw new Error('Options dump failed integrity check.');
    // Check every row against the application's current schema, too.
    const current = new DatabaseSync(':memory:');
    try {
      current.exec(readFileSync(path.join(root, 'database/schema.sql'), 'utf8'));
      // Older installed catalogs omit optional columns introduced by migrations.
      const sourceColumns = new Set(database.prepare('PRAGMA table_info(options)').all().map(column => column.name));
      const columns = current.prepare('PRAGMA table_info(options)').all().map(column => column.name).filter(name => !['primary_write_json', 'writes_json', 'item_init'].includes(name) || sourceColumns.has(name));
      const rows = database.prepare(`SELECT ${columns.map(quoteIdentifier).join(', ')} FROM options ORDER BY id`).all();
      const insert = current.prepare(`INSERT INTO options (${columns.map(quoteIdentifier).join(', ')}) VALUES (${columns.map(() => '?').join(', ')})`);
      for (const row of rows) insert.run(...columns.map(column => row[column]));
      return rows.length;
    } finally { current.close(); }
  } finally { database.close(); }
}

function exportOptions(sourcePath, destination = dumpPath) {
  if (path.resolve(sourcePath) === path.resolve(destination)) throw new Error('The dump must not overwrite its source database.');
  const source = new DatabaseSync(sourcePath, { readOnly: true });
  let sql;
  try {
    // A read transaction includes committed WAL changes and keeps the entire snapshot consistent.
    source.exec('BEGIN');
    const table = source.prepare("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'options'").get();
    if (!table) throw new Error('Source database has no options table.');
    const columns = source.prepare('PRAGMA table_info(options)').all().map(column => column.name);
    const query = source.prepare('SELECT * FROM options ORDER BY id');
    query.setReadBigInts(true);
    const rows = query.all();
    const sequence = source.prepare("SELECT seq FROM sqlite_sequence WHERE name = 'options'");
    sequence.setReadBigInts(true);
    const seq = sequence.get()?.seq ?? 0n;
    const names = columns.map(quoteIdentifier).join(', ');
    sql = [
      '-- Options snapshot for first installation. Generated by npm run options:dump.',
      '-- Contains only options; no presets, settings, or local paths.',
      'BEGIN TRANSACTION;', `${table.sql};`,
      ...rows.map(row => `INSERT INTO "options" (${names}) VALUES (${columns.map(column => sqlValue(row[column])).join(', ')});`),
      "DELETE FROM sqlite_sequence WHERE name = 'options';",
      `INSERT INTO sqlite_sequence (name, seq) VALUES ('options', ${seq});`,
      'COMMIT;'
    ].join('\n\n') + '\n';
    source.exec('COMMIT');
  } finally { source.close(); }
  const count = validateDump(sql);
  const temporary = `${destination}.${process.pid}.tmp`;
  try {
    writeFileSync(temporary, sql, { encoding: 'utf8', flag: 'wx' });
    renameSync(temporary, destination);
  } finally { rmSync(temporary, { force: true }); }
  return count;
}

if (require.main === module) {
  try {
    if (process.argv[2] === '--check') {
      console.log(`Validated release snapshot: ${validateDump(readFileSync(dumpPath, 'utf8'))} options.`);
    } else {
      const source = process.argv[2] || process.env.SOTN_OPTIONS_DATABASE ||
        (process.env.APPDATA && path.join(process.env.APPDATA, 'sotn-preset-generator/options.sqlite'));
      if (!source) throw new Error('Set SOTN_OPTIONS_DATABASE to your options.sqlite path.');
      console.log(`Exported ${exportOptions(source)} options to database/options-dump.sql.`);
    }
  } catch (error) {
    console.error(`Options snapshot failed: ${error.message}`);
    process.exitCode = 1;
  }
}

module.exports = { exportOptions, validateDump };
