import type { JsonObject, Preset, PresetOption, TemplateOptionMatch, WriteEntry } from "./types";
import { detectStartingRelics } from "./starting-relics";

function record(value: unknown): value is JsonObject {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function equal(left: unknown, right: unknown): boolean {
  if (Array.isArray(left) && Array.isArray(right)) return left.length === right.length && left.every((item, index) => equal(item, right[index]));
  if (record(left) && record(right)) {
    const keys = Object.keys(left);
    return keys.length === Object.keys(right).length && keys.every((key) => Object.hasOwn(right, key) && equal(left[key], right[key]));
  }
  return left === right;
}

function numeric(value: unknown): unknown {
  return typeof value === "string" && /^0x[\da-f]+$/i.test(value) ? BigInt(value).toString() : typeof value === "number" ? value.toString() : value;
}

function byteString(value: unknown): unknown {
  return typeof value === "string" && /^(?:[\da-f]{2})*$/i.test(value)
    ? (value.match(/[\da-f]{2}/gi) ?? []).map((byte) => parseInt(byte, 16)) : value;
}

export function writeLocations(writes: WriteEntry[]): { address: number | undefined; startup: boolean }[] {
  let address: number | undefined;
  let startup = false;
  let delaySlot = false;
  return writes.map((write) => {
    if (!record(write)) { address = undefined; startup = false; return { address, startup }; }
    if (write.address !== undefined) {
      const next = Number(write.address);
      if (next === 0x158c98) { startup = true; delaySlot = false; }
      else if (next !== address) startup = false;
      address = Number.isSafeInteger(next) ? next : undefined;
    }
    const location = { address, startup };
    const bytes = byteString(write.value);
    const size = write.type === "string" && Array.isArray(bytes) ? bytes.length
      : ({ char: 1, short: 2, word: 4, long: 8 } as Record<string, number>)[String(write.type)];
    address = address === undefined || size === undefined ? undefined : address + size;
    if (delaySlot) startup = false;
    if (startup && numeric(write.value) === numeric("0x0803924f")) delaySlot = true;
    return location;
  });
}

export function matchTemplateOptions(source: JsonObject, options: PresetOption[]): TemplateOptionMatch[] {
  const writes = Array.isArray(source.writes) ? source.writes.map((write) => record(write) ? write : {}) : [];
  const locations = writeLocations(writes);
  const grantWrites = new Map<string, number[]>();
  const relics = detectStartingRelics(source, grantWrites);
  return options.flatMap<TemplateOptionMatch>((option) => {
    if (option.previewJson) {
      const keys = Object.keys(option.previewJson);
      // These fields are generated by the editor rather than inherited.
      const generated = ["inherits", "lockLocation", "metadata", "relicLocationsExtension", "complexityGoal"];
      if (!keys.length || keys.some((key) => generated.includes(key) || !Object.hasOwn(source, key) || !equal(source[key], option.previewJson![key]))) return [];
      return [{ optionId: option.id, writeIndices: [], jsonKeys: keys }];
    }
    const expected = [...option.injectedWrites, ...option.gameInitWrites, ...option.appendedWrites];
    if (!expected.length) return [];
    const inStartup = option.injectedWrites.length > 0 || option.gameInitWrites.length > 0;
    if (option.category === "relics" && option.label.startsWith("Enable ") && !relics.has(option.label.slice(7))) return [];
    const relicIndices = option.category === "relics" && option.label.startsWith("Enable ") ? grantWrites.get(option.label.slice(7)) : undefined;
    const expectedLocations = writeLocations(expected);
    if (!inStartup && expectedLocations[0].address === undefined) return [];
    const indices = new Set<number>();
    for (let start = 0; start <= writes.length - expected.length; start++) {
      if (relicIndices && !relicIndices.includes(start)) continue;
      const matches = expected.every((write, offset) => {
        const candidate = writes[start + offset];
        const location = locations[start + offset];
        if (inStartup && !location.startup) return false;
        if (candidate.type !== write.type) return false;
        if (write.type === "string" ? !equal(byteString(candidate.value), byteString(write.value)) : numeric(candidate.value) !== numeric(write.value)) return false;
        const expectedAddress = expectedLocations[offset].address;
        if (expectedAddress !== undefined && expectedAddress !== location.address) return false;
        return Object.keys(write).filter((key) => !["comment", "reason", "address", "type", "value"].includes(key)).every((key) => equal(write[key], candidate[key]));
      });
      if (matches) expected.forEach((_write, offset) => indices.add(start + offset));
    }
    return indices.size ? [{ optionId: option.id, writeIndices: [...indices], jsonKeys: [] }] : [];
  });
}

/** Match old drafts once; persisted empty matches preserve later deselections. */
export function selectTemplateOptions(preset: Preset, options: PresetOption[]): Preset {
  if (!preset.baseTemplate || preset.templateOptionMatches !== undefined) return preset;
  const templateOptionMatches = matchTemplateOptions(preset.baseTemplate, options);
  return { ...preset, templateOptionMatches, optionIds: [...new Set([...preset.optionIds, ...templateOptionMatches.map((match) => match.optionId)])] };
}

export function templateWithOptionSelections(preset: Preset): JsonObject | undefined {
  if (!preset.baseTemplate) return undefined;
  const source = structuredClone(preset.baseTemplate);
  const selected = new Set(preset.optionIds);
  const matches = preset.templateOptionMatches ?? [];
  const retainedWrites = new Set(matches.filter((match) => selected.has(match.optionId)).flatMap((match) => match.writeIndices));
  const retainedKeys = new Set(matches.filter((match) => selected.has(match.optionId)).flatMap((match) => match.jsonKeys));
  const removedWrites = new Set(matches.filter((match) => !selected.has(match.optionId)).flatMap((match) => match.writeIndices).filter((index) => !retainedWrites.has(index)));
  for (const match of matches) {
    if (!selected.has(match.optionId)) for (const key of match.jsonKeys) if (!retainedKeys.has(key)) delete source[key];
  }
  if (Array.isArray(source.writes) && removedWrites.size) {
    const writes = source.writes as WriteEntry[];
    const locations = writeLocations(writes);
    source.writes = writes.flatMap((write, index) => {
      if (!record(write)) return [write];
      if (removedWrites.has(index)) {
        // Keep startup instruction positions stable so branches and other
        // patches still address the same code after an option is unchecked.
        return locations[index].startup && write.type === "word"
          ? [{ ...write, value: "0x00000000", comment: "Disabled template option (nop)" }] : [];
      }
      if (index > 0 && removedWrites.has(index - 1) && write.address === undefined && locations[index].address !== undefined) {
        return [{ ...write, address: `0x${locations[index].address!.toString(16)}` }];
      }
      return [write];
    });
  }
  return source;
}
